# Generated by Django 4.0.4 on 2022-08-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodApp', '0006_fileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plat',
            name='plat_national',
            field=models.BooleanField(null=True),
        ),
    ]
