# Generated by Django 4.0.4 on 2022-08-25 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodApp', '0007_alter_plat_plat_national'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fileUpload',
        ),
    ]
